# Generated by Django 4.1.5 on 2023-01-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusiness',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellingproduct',
            name='user_business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userbusiness'),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='user_business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userbusiness'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='user_business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.userbusiness'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_num_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
        migrations.AddField(
            model_name='order',
            name='selling_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sellingproduct'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.paymenttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.userbusiness'),
        ),
    ]
